//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectJob.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class elan
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Location { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> JobTypeId { get; set; }
    
        public virtual JobType JobType { get; set; }
    }
}
