//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectJob.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobsEntities : DbContext
    {
        public jobsEntities()
            : base("name=jobsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vakansiyalar> vakansiyalars { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<elan> elans { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
    }
}
