//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectJob.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class vakansiyalar
    {
        public int vakId { get; set; }
        public string vakAd { get; set; }
        public string vakSeher { get; set; }
        public string vakSirket { get; set; }
        public string VakMaas { get; set; }
        public string vakDate { get; set; }
        public string vakHaqqinda { get; set; }
        public Nullable<int> vakToCategory { get; set; }
        public Nullable<short> active { get; set; }
    }
}
